baseURL = 'https://ethan.ug/'
theme = 'raaijmakers'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
disableHugoGeneratorInject = true

[params]
  avatar = "/images/avatar.jpeg"
  author = "Ethan Timothy"
  images = ["/images/avatar.jpg"]

  [languages]
  [languages.en]
    locale = 'en-us'
    label = 'English'
    weight = 1
    title = 'Ethan Timothy'
    [languages.en.params]
      description = "Personal Portfolio and website of Ethan Timothy, a Social Media Specialist & Frontend Developer from Kiboga, Uganda. I manage media accounts and also build professional websites"
    [languages.en.params.profileMode]
      title = "Wandaye Ethan Timothy"
      subtitle = "Social Media Specialist & Frontend Developer from Kiboga, Uganda. I manage media accounts and also build professional websites."
    [[languages.en.menu.main]]
      name = "Home"
      url = "/"
      weight = 1
    [[languages.en.menu.main]]
      name = "All-Projects"
      url = "/posts/"
      weight = 2
    [[languages.en.menu.main]]
      name = "About"
      url = "/about/"
      weight = 3

[sitemap]
  changefreq = 'weekly'
  priority = 0.5
  